import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://howden.b2ctravel.co.uk/quote');
  await page.getByRole('button', { name: 'Accept Cookies' }).click();
  await page.getByText('Yes', { exact: true }).click();
  await page.locator('#titlepolicyholder').selectOption('1: 1');
  await page.locator('div').filter({ hasText: /^First Name$/ }).getByRole('textbox').click();
  await page.locator('div').filter({ hasText: /^First Name$/ }).getByRole('textbox').fill('AA');
  await page.locator('div').filter({ hasText: /^First Name$/ }).getByRole('textbox').press('Tab');
  await page.locator('#surnamepolicyholder').fill('BB');
  await page.locator('#surnamepolicyholder').press('Tab');
  await page.getByPlaceholder('DD').fill('2');
  await page.getByPlaceholder('DD').press('Tab');
  await page.getByPlaceholder('MM').fill('2');
  await page.getByPlaceholder('MM').press('Tab');
  await page.getByPlaceholder('YYYY').fill('2000');
  await page.getByPlaceholder('YYYY').press('Tab');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('Single Trip', { exact: true }).click();
  await page.getByText('France').click();
  await page.locator('div').filter({ hasText: /^Start Date$/ }).getByRole('button').click();
  await page.getByText('10', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^Return Date$/ }).getByRole('button').click();
  await page.getByText('11', { exact: true }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByText('No', { exact: true }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue with standard' }).click();
  await page.locator('#postcode').click();
  await page.locator('#postcode').fill('cb101aa');
  await page.locator('#postcode').press('Tab');
  await page.locator('input[name="address1"]').press('Tab');
  await page.locator('#postcode').click();
  await page.locator('#postcode').fill('cb10 1aa');
  await page.locator('#postcode').press('Enter');
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').fill('aa@test.com');
  await page.locator('input[name="email"]').press('Tab');
  await page.getByRole('button', { name: 'Save & get quotes' }).click();
  await page.locator('product-premium').filter({ hasText: 'Single Trip£5.27 inc.IPT Buy' }).getByRole('button').first().click();
  await page.getByText('Yes, I agree').click();
  await page.getByPlaceholder('Name on Card').click();
  await page.getByPlaceholder('Name on Card').fill('Developer');
  await page.getByPlaceholder('Name on Card').press('Tab');
  await page.getByPlaceholder('3333 2222 1111').fill('4444333322221111');
  await page.getByPlaceholder('3333 2222 1111').press('Tab');
  await page.getByPlaceholder('MM').fill('1');
  await page.getByPlaceholder('MM').press('Tab');
  await page.getByPlaceholder('YYYY').fill('2025');
  await page.getByPlaceholder('YYYY').press('Tab');
  await page.getByPlaceholder('CVC').fill('123');

});